### PR TITLE
Adrianritchie dynamic ajaxuploadTarget

### PR DESCRIPTION
**Pull request by adrianritchie**
I've made changes to the pre- & post-hooks for FormIt integration to allow the ajaxuploadTarget to contain values from FormIt fields.

### CODE REVIEW

**Comment by adrianritchie** [comment]
As an example, this is how I'm using the changes I've made: ajaxuploadTarget=`images/applications/documentUploads-[[+applicationSessionId]]/`.

applicationSessionId is an internal field that I'm using to associate multiple FormIt forms to create a multi-page form process.  By using this in the ajaxuploadTarget I can segregate the files uploaded by different users to avoid hot-linking or overwriting by different users.

**Comment by Jako** [comment]
I don't think that this is needed. You could modify every snippet property of the FormIt call in a hook by `$hook->formit->config['key']`, so if you want to change the upload target inside another hook, use 
```
$hook->formit->config['ajaxuploadTarget'] = $hook->formit->config['ajaxuploadTarget'] . 'whatever';
```

But if you have an usage case for your patch, that is not covered by the example code above, convince me please.

**Comment by adrianritchie** [comment]
I wasn't aware that was possible.  I'll have a play and see if it does what I need and get back to you.

**Comment by adrianritchie** [comment]
I've verified that the change you suggested works in my scenario.  I have also been able to use it to simplify some other code, so thank you 👍

**Pull request closed without merging**
